version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=arbibot
      - POSTGRES_PASSWORD=arbibot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=YOUR_API_KEY_AQUI  # opcional se precisar de IA
    volumes:
      - .:/app

volumes:
  postgres_data:
